// This file is automatically generated by build.rs

pub const MARKET_API_KEY: &str = "";
pub const MARKET_EOD_ROUTE: &str = "/eod";
pub const MARKET_INDICES_ROUTE: &str = "/indices";
pub const MARKET_QUOTE_ROUTE: &str = "/quote";
pub const MARKET_REAL_TIME_PRICE_ROUTE: &str = "/quotes/price";
pub const MARKET_REST_ADDRESS: &str = "https://api.twelvedata.com";
pub const MARKET_STOCKS_ROUTE: &str = "/stocks";
pub const MARKET_WS_ADDRESS: &str = "wss://ws.twelvedata.com/v1";
