use dotenv::dotenv;
use std::env;
use std::fs::File;
use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=.env");
    let dest_path = "./src/common/env.rs";
    let mut f = File::create(dest_path).unwrap_or_else(|e| {
        eprintln!("cargo::warning=Failed to create {dest_path}: {e}");
        std::process::exit(1);
    });

    // .env is optional; variables from the shell environment take precedence
    dotenv().ok();

    f.write_all(b"// This file is automatically generated by build.rs\n\n")
        .unwrap_or_else(|e| {
            eprintln!("cargo::warning=Failed to write to {dest_path}: {e}");
            std::process::exit(1);
        });
    for (key, value) in env::vars() {
        if key.starts_with("MARKET_") {
            let line = format!(
                "pub const {}: &str = \"{}\";\n",
                key,
                value.replace('"', "\\\"")
            );
            f.write_all(line.as_bytes()).unwrap_or_else(|e| {
                eprintln!("cargo::warning=Failed to write constant {key}: {e}");
                std::process::exit(1);
            });
        }
    }
}
